---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  VERSION: 1.1
  SRC: '**/*.go'
  GOBUILDFLAGS: -v -trimpath
  REV:
    sh: git rev-parse --short HEAD
  LDFLAGS: -w -s -X main.Version={{.VERSION}}.{{.REV}}
  BUILDCMD: go build {{.GOBUILDFLAGS}} -ldflags={{.LDFLAGS}}
  CGO: 0
  # DEMO_IMAGE: ./examples/paintface.src.png
  DEMO_IMAGE: ./examples/ateam.jpg

tasks:

  build:
    cmds:
      - go build
    sources:
      - '{{.SRC}}'
    generates:
      - ./retrospex

  test:
    cmds:
      - go test ./...

  coverage:
    cmds:
      - go test ./... -coverprofile=cover.out
      - go tool cover -html=cover.out

  dist:
    cmds:
      - task: compile
        vars:
          GOOS: darwin
          GOARCH: arm64
          ARCH: macos.arm64
      - task: compile
        vars:
          GOOS: darwin
          GOARCH: amd64
          ARCH: macos.amd64

  zip:
    internal: true
    cmds:
      - 'zip -m 9 {{.FOLDER}} {{.ZIPFILE}}'

  compile:
    internal: true
    vars:
      OUTFILE: retrospex_{{.GOOS}}_{{.GOARCH}}
    cmds:
      - CGO_ENABLED={{.CGO}} GOOS={{.GOOS}} GOARCH={{.GOARCH}} go build {{.GOBUILDFLAGS}}
        -ldflags="{{.LDFLAGS}} -X main.Arch={{.ARCH}}" -o {{.OUTFILE}}

  koala_example:
    deps:
      - build
    vars:
      PNG_OUTPUT: '{{.DEMO_IMAGE}}.koala.png'
      PRG_OUTPUT: '{{.DEMO_IMAGE}}.koala.prg'
    cmds:
      - ./retrospex -m koala -resize -overwrite -o {{.PNG_OUTPUT}} {{.DEMO_IMAGE}}
      - open {{.PNG_OUTPUT}}
      - png2prg --mode koala -display -o {{.PRG_OUTPUT}} {{.PNG_OUTPUT}}
      - open {{.PRG_OUTPUT}}

  hires_example:
    deps:
      - build
    vars:
      PNG_OUTPUT: '{{.DEMO_IMAGE}}.hires.png'
      PRG_OUTPUT: '{{.DEMO_IMAGE}}.hires.prg'
    cmds:
      - ./retrospex -m hires -resize -overwrite -o {{.PNG_OUTPUT}} {{.DEMO_IMAGE}}
      - open {{.PNG_OUTPUT}}
      - png2prg --mode hires -display -o {{.PRG_OUTPUT}} {{.PNG_OUTPUT}}
      - open {{.PRG_OUTPUT}}

  sccharset_example:
    deps:
      - build
    vars:
      PNG_OUTPUT: '{{.DEMO_IMAGE}}.sccharset.png'
      PRG_OUTPUT: '{{.DEMO_IMAGE}}.sccharset.prg'
    cmds:
      - './retrospex -m sccharset -resize -overwrite -o {{.PNG_OUTPUT}} {{.DEMO_IMAGE}}'
      - open {{.PNG_OUTPUT}}
      - png2prg --mode sccharset -display -o {{.PRG_OUTPUT}} {{.PNG_OUTPUT}}
      - open {{.PRG_OUTPUT}}

  clean:
    cmds:
      - rm ./retrospex || true
      - rm retrospex_* || true
